name: Android Dev CI

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean testDebugUnitTestCoverage

      - name: Upload Report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: report.xml
          path: ${{ github.workspace }}/build/reports/jacoco/testDebugUnitTestCoverage.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testDebugUnitTestCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 20
          min-coverage-changed-files: 20
